-- AZLON AI - CAMPAIGNS TABLE UPGRADE
-- Run this in your Supabase SQL Editor to add campaign tracking fields

ALTER TABLE public.campaigns
ADD COLUMN IF NOT EXISTS voice TEXT DEFAULT 'Mark',
ADD COLUMN IF NOT EXISTS positive INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS declined INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS pending INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS failed INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS completed INTEGER DEFAULT 0;
